name: coworking_mobile
description: >
  Highly scalable Flutter starter kit, designed with an optimal predefined structure 
  and inclusive of libraries that are widely applicable in numerous use cases.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.1+3

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.10.5 <4.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  collection: any
  async: any
  meta: any
  intl: any
  flutter_localizations:
    sdk: flutter

  # Stream
  stream_transform: ^2.1.0
  rxdart: ^0.27.7

  # BLoC
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2

  # UI
  dots_indicator: ^3.0.0

  # Routing
  go_router: ^14.0.1

  # Codegen
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Networking
  dio: ^5.3.3

  # Persisting
  shared_preferences: ^2.2.2
  drift: ^2.13.1
  sqlite3_flutter_libs: ^0.5.18

  # Logging
  stack_trace: ^1.11.0
  sentry_flutter: ^7.12.0
  logging: ^1.2.0

  # Utils
  pure: ^0.2.0
  platform_info: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.1.0
  mocktail: ^1.0.1
  flutter_svg: ^2.0.10+1
  mailer: ^6.1.0
  url_launcher: ^6.3.1
  
dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Utils
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5

  # Codegen
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  drift_dev: ^2.13.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/png/
    - assets/images/svg/
    - assets/images/png/rooms_fake/
    - assets/images/png/rooms_details_fake/
    - assets/images/png/room_1/
    - assets/images/png/room_2/
    - assets/images/png/room_3/
    - assets/images/png/room_4/
    - assets/images/png/room_5/
    - assets/images/png/room_6/
    - assets/images/png/cities/istanbul/
    - assets/images/png/cities/moscow/
    - assets/images/png/cities/baku/
  fonts:
    - family: GTEestiProDisplay
      fonts:
        - asset: assets/fonts/GTEestiProDisplay-Bold.otf
          weight: 700
        - asset: assets/fonts/GTEestiProDisplay-Light.otf
          weight: 300
        - asset: assets/fonts/GTEestiProDisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/GTEestiProDisplay-Regular.otf
          weight: 400
        - asset: assets/fonts/GTEestiProDisplay-Thin.otf
        - asset: assets/fonts/GTEestiProDisplay-Ultrabold.otf

flutter_gen:
  output: lib/src/core/constant/generated
  line_length: 80

flutter_launcher_icons:
  image_path: "assets/images/ios_logo.png"
#  image_path_android: "assets/images/icon-1024x1024.png"
#  image_path_ios: "assets/images/icon-1024x1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "#ffffff" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/android_logo.png" # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

  web:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
    # background_color: "#hexcode"
    # theme_color: "#hexcode"

  windows:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
    icon_size: 48 # min:48, max:256, default: 48

  macos:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
